openapi: "3.0.3"
info:
  version: 0.1.0
  title: ATMOS Platform API
  description: Unofficial client for ATMOS Platform API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://localhost/
paths:
  /api/v1/users/{userId}:
    $ref: './paths/users/{userId}.yaml'
  /api/v1/users/{userId}/statistics:
    $ref: './paths/users/{userId}/statistics.yaml'
  /api/v1/divelogs/shortDrafts:
    $ref: './paths/divelogs/shortDrafts.yaml'
  /api/v1/divelogs/deleted:
    $ref: './paths/divelogs/deleted.yaml'
  /api/v1/divelogs/divelog/{divelogId}:
    $ref: './paths/divelog/{divelogId}.yaml'

components:
  securitySchemes:
    $ref: './components/securitySchemes/bearerAuth.yaml'
security:
  - bearerAuth: []
